/**
 * The panel's own version: which one is running, and how to replace it.
 *
 * This deliberately does *not* look like the DSH card next to it, because the
 * two are not the same problem:
 *
 *   - DSH is an npm package. The registry is queried with the user's own npm,
 *     and updating is `npm install -g`.
 *   - The panel is an unsigned Electron app shipped as an installer. There is
 *     nothing to `install -g`; the update is "download the artifact for this
 *     platform and let the user's OS run it".
 *
 * The version feed is electron-builder's own `latest*.yml`, published as a
 * release asset by the Release workflow. Chosen over the GitHub API for one
 * concrete reason observed while building this: the API is rate-limited per IP
 * (60/hour unauthenticated, and this very session hit 403 on it), while a
 * release asset is served like any other file. `latest*.yml` also carries the
 * **sha512 and size** of every artifact, so a download can be verified -- which
 * matters here, because the file being downloaded is handed to the OS to run.
 *
 * Nothing here claims an update was applied. The panel is replaced by the OS
 * installer, so the honest report is "downloaded and handed to the installer".
 */

import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { HttpError } from './errors.mjs';
import {
  DOWNLOAD_TIMEOUT_MS,
  assertFollowable,
  httpDownload,
  httpGetText,
} from './httpGet.mjs';
import { compareSemver, parseSemver } from './semver.mjs';
import { log } from './util.mjs';

/** How long a feed answer is reused. It changes when a release is published. */
const FEED_TTL_MS = 30 * 60 * 1000;

/** The feed is a few hundred bytes; anything larger is not a feed. */
const FEED_MAX_BYTES = 64 * 1024;

/** GitHub asks for a User-Agent and rejects requests without one. */
const FEED_HEADERS = {
  accept: 'text/yaml, text/plain, */*',
  'user-agent': 'dsh-control-panel',
};

// ---------------------------------------------------------------------------
// The feed
// ---------------------------------------------------------------------------

/**
 * electron-builder names its update metadata per platform.
 *
 * Windows gets `latest.yml`, macOS `latest-mac.yml`, Linux `latest-linux.yml`.
 * All three are uploaded by the Release workflow, so whichever one this platform
 * needs is already published.
 */
export function feedFileName(platform = process.platform) {
  if (platform === 'darwin') return 'latest-mac.yml';
  if (platform === 'linux') return 'latest-linux.yml';
  return 'latest.yml';
}

/**
 * Parse electron-builder's `latest*.yml`.
 *
 * Deliberately a targeted regex read rather than a YAML parse: `src/core/` may
 * not import a YAML library, and the file is machine-generated by
 * electron-builder in a fixed shape, so the two things this needs (the version
 * and the file list) are unambiguous. A general parser here would be more code
 * with more ways to be wrong, and the caller validates the result anyway -- an
 * unparseable feed reports "could not read the release feed", never a guessed
 * version.
 *
 * @param {string} text
 * @returns {{version: string, releaseDate: string|null, files: Array<{url: string, sha512: string|null, size: number|null}>}|null}
 */
export function parseFeed(text) {
  const raw = String(text ?? '');
  const version = /^version:\s*['"]?([^'"\s]+)['"]?\s*$/m.exec(raw)?.[1] ?? null;
  const releaseDate = /^releaseDate:\s*['"]?([^'"\s]+)['"]?\s*$/m.exec(raw)?.[1] ?? null;
  if (!version || !parseSemver(version)) return null;

  // Each artifact is a `- url:` entry followed by its own sha512 and size.
  const files = [];
  for (const block of raw.split(/^\s*-\s*url:\s*/m).slice(1)) {
    const lines = block.split(/\r?\n/);
    const url = lines[0].trim().replace(/^['"]|['"]$/g, '');
    if (!url) continue;
    const props = lines.slice(1, 4).join('\n');
    const sha512 = /^\s*sha512:\s*['"]?([^'"\s]+)['"]?\s*$/m.exec(props)?.[1] ?? null;
    const size = Number(/^\s*size:\s*(\d+)\s*$/m.exec(props)?.[1] ?? NaN);
    files.push({ url, sha512, size: Number.isFinite(size) ? size : null });
  }
  if (files.length === 0) return null;

  return { version, releaseDate, files };
}

/** Where a release asset lives. `latest/download` always means the newest. */
export function assetUrl(repo, fileName) {
  return `https://github.com/${repo}/releases/latest/download/${encodeURIComponent(fileName)}`;
}

/** The human-facing release page, for notes and a manual download. */
export function releasePageUrl(repo) {
  return `https://github.com/${repo}/releases/latest`;
}

/**
 * Pick the artifact to install for this platform and architecture.
 *
 * Ordered by what a person actually wants to run, not by what happens to be
 * first in the feed:
 *
 *   - **Windows**: the NSIS `-setup.exe`. The portable build is second on
 *     purpose -- running it would open a second copy rather than upgrade the
 *     installed one.
 *   - **macOS**: the `.dmg`. The `.zip` in the same feed is the format
 *     electron-updater consumes, not something to hand a user.
 *   - **Linux**: the `.AppImage`, falling back to `.deb`.
 *
 * The architecture is part of every artifact name except the Windows portable
 * build, so a mismatch is filtered out here rather than downloaded and then
 * refused by the OS.
 *
 * @param {Array<{url: string, sha512: string|null, size: number|null}>} files
 * @param {string} platform
 * @param {string} arch
 * @returns {{url: string, sha512: string|null, size: number|null, kind: string}|null}
 */
export function pickAsset(files, platform = process.platform, arch = process.arch) {
  /** @type {Record<string, Array<{test: (n: string) => boolean, kind: string}>>} */
  const preferences = {
    win32: [
      { test: (n) => n.endsWith(`-${arch}-setup.exe`), kind: 'installer' },
      { test: (n) => n.endsWith(`-${arch}-portable.exe`), kind: 'portable' },
      { test: (n) => n.endsWith('-portable.exe'), kind: 'portable' },
      { test: (n) => n.endsWith(`-${arch}.zip`), kind: 'archive' },
    ],
    darwin: [
      { test: (n) => n.endsWith(`-${arch}.dmg`), kind: 'installer' },
      { test: (n) => n.endsWith(`-${arch}.zip`), kind: 'archive' },
    ],
    linux: [
      { test: (n) => n.endsWith(`-${arch}.AppImage`), kind: 'installer' },
      { test: (n) => n.endsWith(`-${arch}.deb`), kind: 'package' },
    ],
  };

  for (const candidate of preferences[platform] ?? []) {
    const file = files.find((f) => candidate.test(f.url));
    if (file) return { ...file, kind: candidate.kind };
  }
  return null;
}

// ---------------------------------------------------------------------------
// Cache
// ---------------------------------------------------------------------------

const feedCache = { at: 0, value: null };

/** Forget the cached feed. Exported for tests and for a forced re-check. */
export function invalidateFeedCache() {
  feedCache.at = 0;
  feedCache.value = null;
}

// ---------------------------------------------------------------------------
// State
// ---------------------------------------------------------------------------

/**
 * Ask GitHub what the newest release is.
 *
 * A failure is cached like a success, so a machine that is offline does not pay
 * the timeout on every poll; `fresh` is the way out.
 *
 * @param {import('./config.mjs').PanelConfig} config
 * @param {{fresh?: boolean, env?: NodeJS.ProcessEnv, getText?: typeof httpGetText,
 *          timeoutMs?: number, platform?: string}} [opts]
 */
export async function fetchLatestRelease(config, opts = {}) {
  const fresh = opts.fresh === true;
  if (!fresh && feedCache.value && Date.now() - feedCache.at < FEED_TTL_MS) return feedCache.value;

  const getText = opts.getText ?? httpGetText;
  const url = assetUrl(config.panelRepo, feedFileName(opts.platform));
  const checkedAt = new Date().toISOString();

  try {
    const res = await getText(url, {
      headers: FEED_HEADERS,
      timeoutMs: opts.timeoutMs,
      maxBytes: FEED_MAX_BYTES,
      env: opts.env,
    });
    if (res.status !== 200) {
      throw new Error(`the release feed answered HTTP ${res.status} (has a release been published yet?)`);
    }
    const parsed = parseFeed(res.body);
    if (!parsed) throw new Error('the release feed could not be parsed');

    feedCache.at = Date.now();
    feedCache.value = {
      version: parsed.version,
      releaseDate: parsed.releaseDate,
      files: parsed.files,
      checkedAt,
      feedUrl: url,
      error: null,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    log(`WARN panel update check failed: ${message}`);
    feedCache.at = Date.now();
    feedCache.value = {
      version: null,
      releaseDate: null,
      files: [],
      checkedAt,
      feedUrl: url,
      error: message,
    };
  }
  return feedCache.value;
}

/**
 * Everything the "panel version" card renders.
 *
 * `current` is handed in rather than imported: only the host knows its own
 * version (`app.getVersion()` in Electron, `package.json` under the CLI), and a
 * second copy read here could disagree with the one the About tab already shows.
 *
 * @param {import('./config.mjs').PanelConfig} config
 * @param {{current: string, fresh?: boolean, release?: boolean, packaged?: boolean,
 *          platform?: string, arch?: string, getText?: typeof httpGetText,
 *          env?: NodeJS.ProcessEnv}} opts
 */
export async function buildPanelUpdateState(config, opts = {}) {
  const current = String(opts.current ?? '0.0.0');
  // Only an explicit `release: true` crosses the network; `/api/state` is polled.
  const feed = opts.release === true
    ? await fetchLatestRelease(config, opts)
    : feedCache.value;

  const platform = opts.platform ?? process.platform;
  const arch = opts.arch ?? process.arch;
  const asset = pickAsset(feed?.files ?? [], platform, arch);
  const latest = feed?.version ?? null;
  const compare = latest ? compareSemver(latest, current) : null;

  return {
    current,
    latest,
    updateAvailable: compare !== null && compare > 0,
    // A running version *newer* than the published release (a dev checkout) is
    // its own state: reporting it as "up to date" would be wrong too.
    aheadOfRelease: compare !== null && compare < 0,
    releaseDate: feed?.releaseDate ?? null,
    checkedAt: feed?.checkedAt ?? null,
    checkError: feed?.error ?? null,
    feedUrl: feed?.feedUrl ?? assetUrl(config.panelRepo, feedFileName(platform)),
    releaseUrl: releasePageUrl(config.panelRepo),
    repo: config.panelRepo,
    asset: asset
      ? { name: asset.url, kind: asset.kind, size: asset.size, hasDigest: Boolean(asset.sha512) }
      : null,
    // Whether *this* host can replace itself: only a packaged app has an
    // installer to hand to the OS. A source checkout says so instead of offering
    // a button that would fetch an installer for a program it is not running.
    canUpdate: Boolean(opts.packaged) && Boolean(asset) && compare !== null && compare > 0,
    packaged: Boolean(opts.packaged),
    // Named so the card can explain *why* there is no artifact, instead of
    // showing an empty row.
    platform,
    arch,
    // "Never checked" and "up to date" are different states; the card must not
    // blur them.
    checked: Boolean(feed?.checkedAt),
  };
}

// ---------------------------------------------------------------------------
// Downloading
// ---------------------------------------------------------------------------

/** Guards against two downloads running at once in this process. */
let downloadInFlight = null;

export function isDownloadInFlight() {
  return downloadInFlight !== null;
}

/**
 * Where a downloaded installer is put.
 *
 * The user's Downloads directory when it exists, because the point of
 * downloading an installer is that a person ends up running it -- burying a
 * 110 MB file in a temp directory is not a feature. Falls back to the temp
 * directory when there is no Downloads directory.
 */
export function updateDownloadDir(env = process.env, home = os.homedir()) {
  const override = String(env.DSH_PANEL_DOWNLOAD_DIR ?? '').trim();
  if (override) return path.resolve(override);
  const downloads = path.join(home, 'Downloads');
  try {
    if (fs.statSync(downloads).isDirectory()) return downloads;
  } catch { /* no Downloads directory; fall through */ }
  return path.join(os.tmpdir(), 'dsh-control-panel-update');
}

/** Hash a file without holding it in memory. */
export function sha512Of(filePath) {
  return new Promise((resolve, reject) => {
    const hash = crypto.createHash('sha512');
    const stream = fs.createReadStream(filePath);
    stream.on('data', (c) => hash.update(c));
    stream.on('error', reject);
    stream.on('end', () => resolve(hash.digest('base64')));
  });
}

/**
 * Download the newest artifact and verify it.
 *
 * The digest from the feed is checked. That is a large part of why the feed is
 * the source of truth rather than the GitHub API: this file ends up being
 * executed by the OS, so handing it over after a truncated or tampered download
 * is the one outcome worth refusing. When the feed publishes no digest the
 * download still proceeds, but `verified` is `null` -- the caller says "not
 * verified" rather than implying a check that never happened.
 *
 * @param {import('./config.mjs').PanelConfig} config
 * @param {{current?: string, packaged?: boolean, platform?: string, arch?: string,
 *          env?: NodeJS.ProcessEnv, download?: typeof httpDownload, getText?: typeof httpGetText,
 *          timeoutMs?: number, downloadDir?: string}} [opts]
 */
export async function downloadPanelUpdate(config, opts = {}) {
  if (downloadInFlight) throw new HttpError(409, 'an update download is already running');
  downloadInFlight = 'panel';
  try {
    const platform = opts.platform ?? process.platform;
    const arch = opts.arch ?? process.arch;
    const current = String(opts.current ?? '0.0.0');

    // Read the feed here rather than through `buildPanelUpdateState`: the digest
    // lives on the file entry, and re-deriving it from the cache afterwards
    // would be a second, weaker source of truth.
    const feed = await fetchLatestRelease(config, {
      fresh: true,
      env: opts.env,
      getText: opts.getText,
      platform,
    });
    if (feed.error) throw new HttpError(502, feed.error);
    if (!feed.version) throw new HttpError(502, 'no release has been published yet');

    const asset = pickAsset(feed.files, platform, arch);
    if (!asset) {
      throw new HttpError(501, `release ${feed.version} has no artifact for ${platform}/${arch}`);
    }

    const dir = opts.downloadDir ?? updateDownloadDir(opts.env);
    // The asset name comes from the feed and is about to be used as a path, so
    // it is reduced to its basename: a feed entry containing separators must not
    // be able to write outside the download directory.
    const fileName = path.basename(asset.url);
    if (!fileName || fileName === '.' || fileName === '..') {
      throw new HttpError(502, `the release feed named an unusable file (${asset.url})`);
    }
    const dest = path.join(dir, fileName);

    const download = opts.download ?? httpDownload;
    const url = assetUrl(config.panelRepo, fileName);
    log(`panel update: downloading ${fileName} to ${dest}`);

    const res = await download(url, dest, {
      headers: FEED_HEADERS,
      timeoutMs: opts.timeoutMs ?? DOWNLOAD_TIMEOUT_MS,
      env: opts.env,
      // The asset URL is derived from a release feed, so a redirect is the one
      // place it could move somewhere a release artifact cannot legitimately
      // live. This file is about to be executed by the OS.
      onRedirect: assertFollowable,
    });

    const actual = await sha512Of(dest);
    const verified = asset.sha512 ? actual === asset.sha512 : null;
    if (verified === false) {
      // Never leave a file that failed its digest where a user could run it.
      fs.rmSync(dest, { force: true });
      throw new HttpError(502, `the downloaded ${fileName} did not match the digest published in the release feed`);
    }

    return {
      version: feed.version,
      from: current,
      file: dest,
      dir,
      size: res.bytes,
      // `null` means "the feed published no digest", which is not the same as
      // "checked and fine".
      verified,
      releaseUrl: releasePageUrl(config.panelRepo),
    };
  } finally {
    downloadInFlight = null;
  }
}
